name: Wheel builder

on:
  push:
    branches:
      - develop

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macOS-10.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.4.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install numpy>=1.19
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  build_wheels_macos_arm64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-latest" ]
        python: [3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'develop'

    - uses: actions/setup-python@v2

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.4.0

    - name: Build wheels for Apple Silicon
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BEFORE_BUILD: pip install numpy>=1.19

    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
